
package tanquesjpa;

import javax.swing.JOptionPane;

/**
 * 
 * @author MarianaMorales17235
 * @author DiegoSevilla17238
 */
public final class GUITanques extends javax.swing.JFrame {
    private BaseDatosTanques DB;
    /**
     * Creates new form GUITanques
     */
    public GUITanques() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        DB = new BaseDatosTanques();
        
        DB.recuperarTanques();
        llenarCBoxRegistro();
    }
    
    public void llenarCBoxRegistro(){
        String[] idtanques;
        idtanques = DB.getListaTanques().retornarListaIDTanques();
        
        for(int i=0;i<idtanques.length;i++){
            cboxRegistro.addItem(idtanques[i]);
        }        
    }
    
    public void actualizarCBoxRegistro(){
        cboxRegistro.removeAllItems();
        String[] idtanques;
        idtanques = DB.getListaTanques().retornarListaIDTanques();
        
        for(int i=0;i<idtanques.length;i++){
            cboxRegistro.addItem(idtanques[i]);
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCilindrico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonCilindrico = new javax.swing.JButton();
        tidcil = new javax.swing.JTextField();
        talturacil = new javax.swing.JTextField();
        tradio = new javax.swing.JTextField();
        panelOrtogonal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tidort = new javax.swing.JTextField();
        talturaort = new javax.swing.JTextField();
        tbase = new javax.swing.JTextField();
        tlargo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonOrtogonal = new javax.swing.JButton();
        panelCubico = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tidcub = new javax.swing.JTextField();
        talturacub = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        botonCubico = new javax.swing.JButton();
        panelOperarTanques = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labeltipo = new javax.swing.JLabel();
        panelMunicipio = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cboxMunicipios = new javax.swing.JComboBox<>();
        spinner1 = new javax.swing.JSpinner();
        botonAsignarValvula = new javax.swing.JButton();
        cboxRegistro = new javax.swing.JComboBox<>();
        panelOperarValvulas = new javax.swing.JPanel();
        botonAbrir = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        spinner2 = new javax.swing.JSpinner();
        bInfoTanque = new javax.swing.JButton();
        botonM3 = new javax.swing.JButton();
        botonValvulasCil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acueducto de Albear");

        panelCilindrico.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo tanque cilindrico"));

        jLabel1.setText("ID:");

        jLabel2.setText("Altura:");

        jLabel3.setText("Radio:");

        botonCilindrico.setText("Ingresar tanque cilindrico");
        botonCilindrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCilindricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCilindricoLayout = new javax.swing.GroupLayout(panelCilindrico);
        panelCilindrico.setLayout(panelCilindricoLayout);
        panelCilindricoLayout.setHorizontalGroup(
            panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCilindricoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCilindricoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(botonCilindrico)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCilindricoLayout.createSequentialGroup()
                        .addGroup(panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tidcil, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(talturacil)
                            .addComponent(tradio))
                        .addContainerGap())))
        );
        panelCilindricoLayout.setVerticalGroup(
            panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCilindricoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tidcil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(talturacil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tradio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(botonCilindrico))
        );

        panelOrtogonal.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo tanque ortogonal"));

        jLabel4.setText("ID:");

        jLabel5.setText("Altura:");

        jLabel6.setText("Base:");

        jLabel7.setText("Largo:");

        botonOrtogonal.setText("Ingresar tanque ortogonal");
        botonOrtogonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrtogonalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOrtogonalLayout = new javax.swing.GroupLayout(panelOrtogonal);
        panelOrtogonal.setLayout(panelOrtogonalLayout);
        panelOrtogonalLayout.setHorizontalGroup(
            panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrtogonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOrtogonalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(botonOrtogonal))
                    .addGroup(panelOrtogonalLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tlargo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrtogonalLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tidort, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrtogonalLayout.createSequentialGroup()
                            .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addGap(10, 10, 10)
                            .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(talturaort, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tbase, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelOrtogonalLayout.setVerticalGroup(
            panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrtogonalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tidort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(talturaort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tlargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonOrtogonal)
                .addGap(24, 24, 24))
        );

        panelCubico.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo tanque cubico"));

        jLabel8.setText("ID:");

        jLabel9.setText("Altura:");

        botonCubico.setText("Ingresar tanque cubico");
        botonCubico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCubicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCubicoLayout = new javax.swing.GroupLayout(panelCubico);
        panelCubico.setLayout(panelCubicoLayout);
        panelCubicoLayout.setHorizontalGroup(
            panelCubicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCubicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCubicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCubicoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tidcub, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCubicoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(talturacub, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCubicoLayout.createSequentialGroup()
                        .addComponent(botonCubico)
                        .addGap(10, 10, 10)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelCubicoLayout.setVerticalGroup(
            panelCubicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCubicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCubicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tidcub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCubicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(talturacub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCubico)
                .addGap(18, 18, 18))
        );

        panelOperarTanques.setBorder(javax.swing.BorderFactory.createTitledBorder("Operar tanques"));

        jLabel10.setText("Tanques del registro");

        labeltipo.setText("     -----------------");

        panelMunicipio.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignar municipio a valvula"));

        jLabel12.setText("Numero de valvula:");

        jLabel13.setText("Municipio:");

        spinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        botonAsignarValvula.setText("Asignar municipio");
        botonAsignarValvula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarValvulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMunicipioLayout = new javax.swing.GroupLayout(panelMunicipio);
        panelMunicipio.setLayout(panelMunicipioLayout);
        panelMunicipioLayout.setHorizontalGroup(
            panelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMunicipioLayout.createSequentialGroup()
                .addGroup(panelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMunicipioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelMunicipioLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMunicipioLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(cboxMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelMunicipioLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(botonAsignarValvula)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMunicipioLayout.setVerticalGroup(
            panelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMunicipioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cboxMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonAsignarValvula)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cboxRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxRegistroActionPerformed(evt);
            }
        });

        panelOperarValvulas.setBorder(javax.swing.BorderFactory.createTitledBorder("Operar valvulas"));

        botonAbrir.setText("Abrir");
        botonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbrirActionPerformed(evt);
            }
        });

        botonCerrar.setText("Cerrar");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        jLabel14.setText("Numero de valvula:");

        spinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        javax.swing.GroupLayout panelOperarValvulasLayout = new javax.swing.GroupLayout(panelOperarValvulas);
        panelOperarValvulas.setLayout(panelOperarValvulasLayout);
        panelOperarValvulasLayout.setHorizontalGroup(
            panelOperarValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperarValvulasLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelOperarValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(botonAbrir))
                .addGap(27, 27, 27)
                .addGroup(panelOperarValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOperarValvulasLayout.setVerticalGroup(
            panelOperarValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperarValvulasLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelOperarValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(panelOperarValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAbrir)
                    .addComponent(botonCerrar))
                .addContainerGap())
        );

        bInfoTanque.setText("Info. Tanque");
        bInfoTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInfoTanqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOperarTanquesLayout = new javax.swing.GroupLayout(panelOperarTanques);
        panelOperarTanques.setLayout(panelOperarTanquesLayout);
        panelOperarTanquesLayout.setHorizontalGroup(
            panelOperarTanquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperarTanquesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelOperarTanquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelOperarTanquesLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(29, 29, 29)
                        .addComponent(cboxRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelOperarValvulas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMunicipio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelOperarTanquesLayout.createSequentialGroup()
                        .addComponent(bInfoTanque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labeltipo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOperarTanquesLayout.setVerticalGroup(
            panelOperarTanquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperarTanquesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelOperarTanquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cboxRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOperarTanquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeltipo)
                    .addComponent(bInfoTanque))
                .addGap(23, 23, 23)
                .addComponent(panelMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelOperarValvulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        botonM3.setText("m3 disponibles");
        botonM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonM3ActionPerformed(evt);
            }
        });

        botonValvulasCil.setText("Valvulas Cilindricos");
        botonValvulasCil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonValvulasCilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCubico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCilindrico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOrtogonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonValvulasCil)
                        .addGap(72, 72, 72)
                        .addComponent(botonM3))
                    .addComponent(panelOperarTanques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelOperarTanques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonValvulasCil)
                            .addComponent(botonM3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCilindrico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(panelOrtogonal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelCubico, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOrtogonal.getAccessibleContext().setAccessibleName("");
        panelOrtogonal.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCilindricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCilindricoActionPerformed
        // TODO add your handling code here:
        String id = tidcil.getText();
        String altura = talturacil.getText();
        String radio = tradio.getText();
        
        if(id.length()==0 || altura.length()==0 || radio.length()==0){
            JOptionPane.showMessageDialog(null, "No deje campos vacios.", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            double alturad = Double.parseDouble(altura);
            double radiod = Double.parseDouble(radio);
            DB.nuevoTanqueCilindrico(id, alturad, radiod);
            actualizarCBoxRegistro();
            JOptionPane.showMessageDialog(null, "Se ha ingresado un nuevo tanque cilindrico exitosamente.", "Tanque Cilindrico Ingresado", JOptionPane.INFORMATION_MESSAGE);            
        }
    }//GEN-LAST:event_botonCilindricoActionPerformed

    private void botonOrtogonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrtogonalActionPerformed
        // TODO add your handling code here:
        String id = tidort.getText();
        String altura = talturaort.getText();
        String largo = tlargo.getText();
        String base = tbase.getText();
        
        if(id.length()==0 || altura.length()==0 || largo.length()==0 || base.length()==0){
            JOptionPane.showMessageDialog(null, "No deje campos vacios.", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            double alturad = Double.parseDouble(altura);
            double largod = Double.parseDouble(largo);
            double based = Double.parseDouble(base);
            DB.nuevoTanqueOrtogonal(id, based, largod, alturad);
            actualizarCBoxRegistro();
            JOptionPane.showMessageDialog(null, "Se ha ingresado un nuevo tanque ortogonal exitosamente.", "Tanque Ortogonal Ingresado", JOptionPane.INFORMATION_MESSAGE);            
        }
    }//GEN-LAST:event_botonOrtogonalActionPerformed

    private void botonCubicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCubicoActionPerformed
        // TODO add your handling code here:
        String id = tidcub.getText();
        String altura = talturacub.getText();
        
        if(id.length()==0 || altura.length()==0){
            JOptionPane.showMessageDialog(null, "No deje campos vacios.", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            double alturad = Double.parseDouble(altura);
            DB.nuevoTanqueCubico(id, alturad);
            actualizarCBoxRegistro();
            JOptionPane.showMessageDialog(null, "Se ha ingresado un nuevo tanque cubico exitosamente.", "Tanque Cubico Ingresado", JOptionPane.INFORMATION_MESSAGE);            
        }
    }//GEN-LAST:event_botonCubicoActionPerformed

    private void cboxRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxRegistroActionPerformed
        // TODO add your handling code here:
        String ID = cboxRegistro.getSelectedItem().toString();
        Tanque tanq = DB.getListaTanques().getTanqueBuscado(ID);
        if(tanq instanceof TCilindrico){
            labeltipo.setText("Tanque Cilindrico");
        }else if(tanq instanceof TCubico){
            labeltipo.setText("Tanque Cubico");
        }else if(tanq instanceof TOrtogonal){
            labeltipo.setText("Tanque Ortogonal");
        }
    }//GEN-LAST:event_cboxRegistroActionPerformed

    private void botonAsignarValvulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarValvulaActionPerformed
        // TODO add your handling code here:
        String ID = cboxRegistro.getSelectedItem().toString();
        String numvalvulaStr = spinner1.getValue().toString();
        String municipio = cboxMunicipios.getSelectedItem().toString();
        
        int numvalvula = Integer.parseInt(numvalvulaStr);
        
    }//GEN-LAST:event_botonAsignarValvulaActionPerformed

    private void botonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirActionPerformed
        // TODO add your handling code here:
        String ID = cboxRegistro.getSelectedItem().toString();
        String numvalvulaStr = spinner2.getValue().toString();
        int numvalvula = Integer.parseInt(numvalvulaStr);
        boolean estadovalv = DB.getListaTanques().getTanqueBuscado(ID).getEstadoAlgunaValvula(numvalvula);  
        Tanque tanq = DB.getListaTanques().getTanqueBuscado(ID);
        //Variables que almacenan algunas especificaciones del tanque.
        double cap = tanq.getCapacidad();
        double temp = tanq.getVolumenTemporal();
        double min = tanq.getVolumenMinimo();
        
        
        if(estadovalv == true){
            JOptionPane.showMessageDialog(null, "Esta valvula ya esta ABIERTA.", "Valvula Abierta", JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(tanq instanceof TCilindrico){
                DB.abrirValvulaAlgunTanqueCil(ID, numvalvula);
            }else if(tanq instanceof TCubico){
                DB.abrirValvulaAlgunTanqueCub(ID, numvalvula);
            }else if(tanq instanceof TOrtogonal){
                DB.abrirValvulaAlgunTanqueOrt(ID, numvalvula);
            }
        }
        
    }//GEN-LAST:event_botonAbrirActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        // TODO add your handling code here:
        String ID = cboxRegistro.getSelectedItem().toString();
        String numvalvulaStr = spinner2.getValue().toString();
        int numvalvula = Integer.parseInt(numvalvulaStr);
        boolean estadovalv = DB.getListaTanques().getTanqueBuscado(ID).getEstadoAlgunaValvula(numvalvula);  
        Tanque tanq = DB.getListaTanques().getTanqueBuscado(ID);
        
        if(estadovalv == true){
            JOptionPane.showMessageDialog(null, "Esta valvula ya esta CERRADA.", "Valvula Cerrada", JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(tanq instanceof TCilindrico){
                DB.cerrarValvulaAlgunTanqueCil(ID, numvalvula);
            }else if(tanq instanceof TCubico){
                DB.cerrarValvulaAlgunTanqueCub(ID, numvalvula);
            }else if(tanq instanceof TOrtogonal){
                DB.cerrarValvulaAlgunTanqueOrt(ID, numvalvula);
            }
        }
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonValvulasCilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonValvulasCilActionPerformed
        // TODO add your handling code here:
        int valvulas = DB.getListaTanques().cantidadValvulasCilindricos();
        JOptionPane.showMessageDialog(null, "El numero de valvulas abiertas en los tanques cilindricos de la region"
                + "es de: "+valvulas+ " valvulas");
    }//GEN-LAST:event_botonValvulasCilActionPerformed

    private void botonM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonM3ActionPerformed
        // TODO add your handling code here:
        double m3disponibles = DB.getListaTanques().calcular_m3_disponibles();
        JOptionPane.showMessageDialog(null, "Actualmente hay "+m3disponibles+" metros cubicos disponibles de liquido para la region.");
    }//GEN-LAST:event_botonM3ActionPerformed

    private void bInfoTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInfoTanqueActionPerformed
        // TODO add your handling code here:
        String ID = cboxRegistro.getSelectedItem().toString(); 
        Tanque tanq = DB.getListaTanques().getTanqueBuscado(ID);
        
        infoTanque infot = new infoTanque();
        if(tanq instanceof TCilindrico){
            infoTanque.jTextArea1.append("Tanque Cilindrico, ID "+tanq.getID());
        }else if(tanq instanceof TCubico){
            infoTanque.jTextArea1.append("Tanque Cubico, ID "+tanq.getID());
        }else if(tanq instanceof TOrtogonal){
            infoTanque.jTextArea1.append("Tanque Ortogonal, ID "+tanq.getID());
        }
        infoTanque.jTextArea1.append(System.getProperty("line.separator"));
        infoTanque.jTextArea1.append(System.getProperty("line.separator"));
        infoTanque.jTextArea1.append("Estado de Valvulas: ");
        infoTanque.jTextArea1.append(System.getProperty("line.separator"));
        
        int count = 1;
        Valvula valv = new Valvula();
        for(int i=0;i<tanq.getValvulas().length;i++){
            valv = tanq.getValvulas()[i];
            if(valv.getEstado()==true){
                infoTanque.jTextArea1.append("Valvula "+count+": Abierta");
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
            }else{
                infoTanque.jTextArea1.append("Valvula "+count+": Cerrada");
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
            }            
            count++;
        }   
        infot.setVisible(true);
    }//GEN-LAST:event_bInfoTanqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITanques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITanques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITanques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITanques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITanques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInfoTanque;
    private javax.swing.JButton botonAbrir;
    private javax.swing.JButton botonAsignarValvula;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonCilindrico;
    private javax.swing.JButton botonCubico;
    private javax.swing.JButton botonM3;
    private javax.swing.JButton botonOrtogonal;
    private javax.swing.JButton botonValvulasCil;
    private javax.swing.JComboBox<String> cboxMunicipios;
    private javax.swing.JComboBox<String> cboxRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labeltipo;
    private javax.swing.JPanel panelCilindrico;
    private javax.swing.JPanel panelCubico;
    private javax.swing.JPanel panelMunicipio;
    private javax.swing.JPanel panelOperarTanques;
    private javax.swing.JPanel panelOperarValvulas;
    private javax.swing.JPanel panelOrtogonal;
    private javax.swing.JSpinner spinner1;
    private javax.swing.JSpinner spinner2;
    private javax.swing.JTextField talturacil;
    private javax.swing.JTextField talturacub;
    private javax.swing.JTextField talturaort;
    private javax.swing.JTextField tbase;
    private javax.swing.JTextField tidcil;
    private javax.swing.JTextField tidcub;
    private javax.swing.JTextField tidort;
    private javax.swing.JTextField tlargo;
    private javax.swing.JTextField tradio;
    // End of variables declaration//GEN-END:variables
}
