
package tanquesjpa;

import javax.swing.JOptionPane;
import java.lang.NumberFormatException;

/**
 * 
 * @author MarianaMorales17235
 * @author DiegoSevilla17238
 */
public final class GUITanques extends javax.swing.JFrame {
    private final BaseDatosTanques DB;
    /**
     * Creates new form GUITanques
     */
    public GUITanques() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        DB = new BaseDatosTanques();
        
        DB.recuperarTanques();
        llenarCBoxRegistro();
    }
    
    public void llenarCBoxRegistro(){
        String[] idtanques = DB.getListaTanques().retornarListaIDTanques();
        cboxRegistro.addItem("");
        for(int i=0;i<idtanques.length;i++){
            cboxRegistro.addItem(idtanques[i]);
        }        
    }
    
    public void actualizarCBoxRegistro(){
        cboxRegistro.removeAllItems();
        String[] idtanques = DB.getListaTanques().retornarListaIDTanques();
        cboxRegistro.addItem("");
        for(int i=0;i<idtanques.length;i++){
            cboxRegistro.addItem(idtanques[i]);
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCilindrico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bCilindrico = new javax.swing.JButton();
        tidcil = new javax.swing.JTextField();
        talturacil = new javax.swing.JTextField();
        tradio = new javax.swing.JTextField();
        panelOrtogonal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tidort = new javax.swing.JTextField();
        talturaort = new javax.swing.JTextField();
        tbase = new javax.swing.JTextField();
        tlargo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bOrtogonal = new javax.swing.JButton();
        panelCubico = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tidcub = new javax.swing.JTextField();
        talturacub = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bCubico = new javax.swing.JButton();
        panelOperarTanques = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labeltipo = new javax.swing.JLabel();
        panelMunicipio = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cboxMunicipios = new javax.swing.JComboBox<>();
        spinner1 = new javax.swing.JSpinner();
        bAsignarMunicipioValvula = new javax.swing.JButton();
        cboxRegistro = new javax.swing.JComboBox<>();
        panelOperarValvulas = new javax.swing.JPanel();
        bAbrir = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        spinner2 = new javax.swing.JSpinner();
        bInfo = new javax.swing.JButton();
        bM3 = new javax.swing.JButton();
        bValvulasCil = new javax.swing.JButton();
        bReestablecer = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        btanquesRegion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acueducto de Albear");

        panelCilindrico.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nuevo tanque cilindrico"));

        jLabel1.setText("ID:");

        jLabel2.setText("Altura:");

        jLabel3.setText("Radio:");

        bCilindrico.setText("Ingresar tanque cilindrico");
        bCilindrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCilindricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCilindricoLayout = new javax.swing.GroupLayout(panelCilindrico);
        panelCilindrico.setLayout(panelCilindricoLayout);
        panelCilindricoLayout.setHorizontalGroup(
            panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCilindricoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bCilindrico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelCilindricoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tidcil, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(talturacil, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tradio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        panelCilindricoLayout.setVerticalGroup(
            panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCilindricoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tidcil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(talturacil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCilindricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tradio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(bCilindrico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOrtogonal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nuevo tanque ortogonal"));

        jLabel4.setText("ID:");

        jLabel5.setText("Altura:");

        jLabel6.setText("Base:");

        jLabel7.setText("Largo:");

        bOrtogonal.setText("Ingresar tanque ortogonal");
        bOrtogonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrtogonalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOrtogonalLayout = new javax.swing.GroupLayout(panelOrtogonal);
        panelOrtogonal.setLayout(panelOrtogonalLayout);
        panelOrtogonalLayout.setHorizontalGroup(
            panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrtogonalLayout.createSequentialGroup()
                .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOrtogonalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bOrtogonal))
                    .addGroup(panelOrtogonalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrtogonalLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tidort, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrtogonalLayout.createSequentialGroup()
                                .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(10, 10, 10)
                                .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(talturaort, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbase, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tlargo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOrtogonalLayout.setVerticalGroup(
            panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrtogonalLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tidort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(talturaort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOrtogonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tlargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bOrtogonal)
                .addGap(19, 19, 19))
        );

        panelCubico.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nuevo tanque cubico"));

        jLabel8.setText("ID:");

        jLabel9.setText("Altura:");

        bCubico.setText("Ingresar tanque cubico");
        bCubico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCubicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCubicoLayout = new javax.swing.GroupLayout(panelCubico);
        panelCubico.setLayout(panelCubicoLayout);
        panelCubicoLayout.setHorizontalGroup(
            panelCubicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCubicoLayout.createSequentialGroup()
                .addGroup(panelCubicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCubicoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCubicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCubicoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tidcub, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCubicoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(talturacub, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelCubicoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(bCubico)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelCubicoLayout.setVerticalGroup(
            panelCubicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCubicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCubicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tidcub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCubicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(talturacub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(bCubico)
                .addContainerGap())
        );

        panelOperarTanques.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Operar tanques"));

        jLabel10.setText("Tanques del registro");

        labeltipo.setText("     -----------------");

        panelMunicipio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Asignar municipio a valvula"));

        jLabel12.setText("Numero de valvula:");

        jLabel13.setText("Municipio:");

        cboxMunicipios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guatemala", "Palencia", "Chinautla", "Mixco", "Quetzaltenango", "Almolonga", "Cantel", "Coatepeque", "Retalhuleu", "Champerico", "San Felipe", "El asintal" }));

        spinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        bAsignarMunicipioValvula.setText("Asignar municipio");
        bAsignarMunicipioValvula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAsignarMunicipioValvulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMunicipioLayout = new javax.swing.GroupLayout(panelMunicipio);
        panelMunicipio.setLayout(panelMunicipioLayout);
        panelMunicipioLayout.setHorizontalGroup(
            panelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMunicipioLayout.createSequentialGroup()
                .addGroup(panelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMunicipioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelMunicipioLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMunicipioLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(cboxMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelMunicipioLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(bAsignarMunicipioValvula)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMunicipioLayout.setVerticalGroup(
            panelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMunicipioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMunicipioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cboxMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bAsignarMunicipioValvula)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cboxRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxRegistroActionPerformed(evt);
            }
        });

        panelOperarValvulas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Operar valvulas"));

        bAbrir.setBackground(new java.awt.Color(51, 255, 0));
        bAbrir.setText("Abrir");
        bAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbrirActionPerformed(evt);
            }
        });

        bCerrar.setBackground(new java.awt.Color(255, 0, 0));
        bCerrar.setText("Cerrar");
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });

        jLabel14.setText("Numero de valvula:");

        spinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        javax.swing.GroupLayout panelOperarValvulasLayout = new javax.swing.GroupLayout(panelOperarValvulas);
        panelOperarValvulas.setLayout(panelOperarValvulasLayout);
        panelOperarValvulasLayout.setHorizontalGroup(
            panelOperarValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperarValvulasLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelOperarValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(bAbrir))
                .addGap(27, 27, 27)
                .addGroup(panelOperarValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOperarValvulasLayout.setVerticalGroup(
            panelOperarValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperarValvulasLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelOperarValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(panelOperarValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAbrir)
                    .addComponent(bCerrar))
                .addContainerGap())
        );

        bInfo.setText("Info. Tanque");
        bInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOperarTanquesLayout = new javax.swing.GroupLayout(panelOperarTanques);
        panelOperarTanques.setLayout(panelOperarTanquesLayout);
        panelOperarTanquesLayout.setHorizontalGroup(
            panelOperarTanquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperarTanquesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelOperarTanquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelOperarTanquesLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(29, 29, 29)
                        .addComponent(cboxRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelOperarValvulas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMunicipio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelOperarTanquesLayout.createSequentialGroup()
                        .addComponent(bInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labeltipo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOperarTanquesLayout.setVerticalGroup(
            panelOperarTanquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperarTanquesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelOperarTanquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cboxRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOperarTanquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeltipo)
                    .addComponent(bInfo))
                .addGap(23, 23, 23)
                .addComponent(panelMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOperarValvulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bM3.setText("m3 disponibles");
        bM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bM3ActionPerformed(evt);
            }
        });

        bValvulasCil.setText("Valvulas Cilindricos");
        bValvulasCil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValvulasCilActionPerformed(evt);
            }
        });

        bReestablecer.setText("Reestablecer Tanque");
        bReestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReestablecerActionPerformed(evt);
            }
        });

        bSalir.setText("SALIR");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        btanquesRegion.setText("Tanques en la region");
        btanquesRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btanquesRegionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelOrtogonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCubico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCilindrico, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bValvulasCil)
                        .addGap(72, 72, 72)
                        .addComponent(bM3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(bReestablecer))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btanquesRegion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSalir))
                        .addComponent(panelOperarTanques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCilindrico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(panelOrtogonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelCubico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btanquesRegion)
                            .addComponent(bSalir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelOperarTanques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bValvulasCil)
                            .addComponent(bM3))
                        .addGap(11, 11, 11)
                        .addComponent(bReestablecer)))
                .addContainerGap())
        );

        panelOrtogonal.getAccessibleContext().setAccessibleName("");
        panelOrtogonal.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCilindricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCilindricoActionPerformed
        // TODO add your handling code here:
        try{
        String id = tidcil.getText();
        String altura = talturacil.getText();
        String radio = tradio.getText();
        
        if(id.length()==0 || altura.length()==0 || radio.length()==0){
            JOptionPane.showMessageDialog(null, "No deje campos vacios.", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            double alturad = Double.parseDouble(altura);
            double radiod = Double.parseDouble(radio);
            DB.nuevoTanqueCilindrico(id, alturad, radiod);
            actualizarCBoxRegistro();
            JOptionPane.showMessageDialog(null, "Se ha ingresado un nuevo tanque cilindrico exitosamente.", "Tanque Cilindrico Ingresado", JOptionPane.INFORMATION_MESSAGE);            
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Se ha ingresado un valor incorrecto en los campos de texto.\n"
                    + "Vuelva a intentarlo.", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bCilindricoActionPerformed

    private void bOrtogonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrtogonalActionPerformed
        // TODO add your handling code here:
        try{
        String id = tidort.getText();
        String altura = talturaort.getText();
        String largo = tlargo.getText();
        String base = tbase.getText();
        
        if(id.length()==0 || altura.length()==0 || largo.length()==0 || base.length()==0){
            JOptionPane.showMessageDialog(null, "No deje campos vacios.", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            double alturad = Double.parseDouble(altura);
            double largod = Double.parseDouble(largo);
            double based = Double.parseDouble(base);
            DB.nuevoTanqueOrtogonal(id, based, largod, alturad);
            actualizarCBoxRegistro();
            JOptionPane.showMessageDialog(null, "Se ha ingresado un nuevo tanque ortogonal exitosamente.", "Tanque Ortogonal Ingresado", JOptionPane.INFORMATION_MESSAGE);            
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Se ha ingresado un valor incorrecto en los campos de texto.\n"
                    + "Vuelva a intentarlo.", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bOrtogonalActionPerformed

    private void bCubicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCubicoActionPerformed
        // TODO add your handling code here:
        try{
        String id = tidcub.getText();
        String altura = talturacub.getText();
        
        if(id.length()==0 || altura.length()==0){
            JOptionPane.showMessageDialog(null, "No deje campos vacios.", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            double alturad = Double.parseDouble(altura);
            DB.nuevoTanqueCubico(id, alturad);
            actualizarCBoxRegistro();
            JOptionPane.showMessageDialog(null, "Se ha ingresado un nuevo tanque cubico exitosamente.", "Tanque Cubico Ingresado", JOptionPane.INFORMATION_MESSAGE);            
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Se ha ingresado un valor incorrecto en los campos de texto.\n"
                    + "Vuelva a intentarlo.", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bCubicoActionPerformed

    private void cboxRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxRegistroActionPerformed
        // TODO add your handling code here:
        try{
            String ID = cboxRegistro.getSelectedItem().toString();
            Tanque tanq = DB.getListaTanques().getTanqueBuscado(ID);
            if(tanq instanceof TCilindrico){
                labeltipo.setText("Tanque Cilindrico");
            }else if(tanq instanceof TCubico){
                labeltipo.setText("Tanque Cubico");
            }else if(tanq instanceof TOrtogonal){
                labeltipo.setText("Tanque Ortogonal");
            }
        }catch(Exception e){
            labeltipo.setText("--------------");
        }
    }//GEN-LAST:event_cboxRegistroActionPerformed

    private void bAsignarMunicipioValvulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAsignarMunicipioValvulaActionPerformed
        // TODO add your handling code here:
        try{
        String ID = cboxRegistro.getSelectedItem().toString();
        String numvalvulaStr = spinner1.getValue().toString();
        String municipio = cboxMunicipios.getSelectedItem().toString();
        int numvalvula = Integer.parseInt(numvalvulaStr);
        
        Tanque tanq = DB.getListaTanques().getTanqueBuscado(ID);        
        
        DB.asignarMuniValvulaTanque(ID, numvalvula, municipio, tanq);
       
        JOptionPane.showMessageDialog(null, "Asignacion de municipio a valvula exitosa.", "", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No hay ningun item seleccionado en el combo box del registro.");
        }
    }//GEN-LAST:event_bAsignarMunicipioValvulaActionPerformed

    private void bAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbrirActionPerformed
        // TODO add your handling code here:
        try{
        String ID = cboxRegistro.getSelectedItem().toString();
        String numvalvulaStr = spinner2.getValue().toString();
        int numvalvula = Integer.parseInt(numvalvulaStr);
        boolean estadovalv = DB.getListaTanques().getTanqueBuscado(ID).getEstadoAlgunaValvula(numvalvula);  
        Tanque tanq = DB.getListaTanques().getTanqueBuscado(ID);
        //Variables que representan algunas especificaciones del tanque.
        double temp = tanq.getVolumenTemporal();
        double min = tanq.getVolumenMinimo();
        
        if(estadovalv == true){
            JOptionPane.showMessageDialog(null, "Esta valvula ya esta ABIERTA.", "Valvula Abierta", JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(temp <= min){        
                
                DB.cerrarTodasValvulasTanque(ID, tanq);
                
                JOptionPane.showMessageDialog(null, "La cantidad de liquido actual del tanque es menor\n"
                        + "al 25% de su capacidad. Todas sus valvulas se han cerrado.\n"
                        + "Si desea volver a operar el tanque oprima 'Reestablecer Tanque'", "", JOptionPane.INFORMATION_MESSAGE);
            }else{
                
                DB.abrirValvulaAlgunTanque(ID, numvalvula, tanq);
                
                JOptionPane.showMessageDialog(null, "La valvula se ha abierto");
            }
        }     
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No hay ningun item seleccionado en el combo box del registro.");
        }
    }//GEN-LAST:event_bAbrirActionPerformed

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        // TODO add your handling code here:
        try{
        String ID = cboxRegistro.getSelectedItem().toString();
        String numvalvulaStr = spinner2.getValue().toString();
        int numvalvula = Integer.parseInt(numvalvulaStr);
        boolean estadovalv = DB.getListaTanques().getTanqueBuscado(ID).getEstadoAlgunaValvula(numvalvula);  
        Tanque tanq = DB.getListaTanques().getTanqueBuscado(ID);
        
        if(estadovalv == false){
            JOptionPane.showMessageDialog(null, "Esta valvula ya esta CERRADA.", "Valvula Cerrada", JOptionPane.INFORMATION_MESSAGE);
        }else{
            
            DB.cerrarValvulaAlgunTanque(ID, numvalvula, tanq);
            
            JOptionPane.showMessageDialog(null, "La valvula se ha cerrado");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No hay ningun item seleccionado en el combo box del registro.");
        }
    }//GEN-LAST:event_bCerrarActionPerformed

    private void bValvulasCilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValvulasCilActionPerformed
        // TODO add your handling code here:
        int valvulas = DB.getListaTanques().cantidadValvulasCilindricos();
        JOptionPane.showMessageDialog(null, "Actualemente hay "+valvulas+" valvulas abiertas en\n"
                + "los tanques cilindricos de la region.");
    }//GEN-LAST:event_bValvulasCilActionPerformed

    private void bM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bM3ActionPerformed
        // TODO add your handling code here:
        double m3disponibles = DB.getListaTanques().calcular_m3_disponibles();
        JOptionPane.showMessageDialog(null, "Actualmente hay "+m3disponibles+" metros cubicos disponibles \nde liquido para la region.");
    }//GEN-LAST:event_bM3ActionPerformed

    private void bInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInfoActionPerformed
        // TODO add your handling code here:
        try{
        String ID = cboxRegistro.getSelectedItem().toString(); 
        Tanque tanq = DB.getListaTanques().getTanqueBuscado(ID);
        
        infoTanque infot = new infoTanque();
        if(tanq instanceof TCilindrico){
            infoTanque.jTextArea1.append("Tanque Cilindrico, ID "+tanq.getIdentificacion());
        }else if(tanq instanceof TCubico){
            infoTanque.jTextArea1.append("Tanque Cubico, ID "+tanq.getIdentificacion());
        }else if(tanq instanceof TOrtogonal){
            infoTanque.jTextArea1.append("Tanque Ortogonal, ID "+tanq.getIdentificacion());
        }
        infoTanque.jTextArea1.append(System.getProperty("line.separator"));
        infoTanque.jTextArea1.append("* Capacidad: "+tanq.getCapacidad());
        infoTanque.jTextArea1.append(System.getProperty("line.separator"));
        infoTanque.jTextArea1.append("* Volumen de Agua Actual: "+tanq.getVolumenTemporal());
        infoTanque.jTextArea1.append(System.getProperty("line.separator"));
        infoTanque.jTextArea1.append("* Estado de Valvulas: ");
        infoTanque.jTextArea1.append(System.getProperty("line.separator"));
        
        int count = 1;
        Valvula valv = new Valvula();
        for(int i=0;i<tanq.getValvulas().length;i++){
            valv = tanq.getValvulas()[i];
            if(valv.getEstado()==true){
                if(valv.getMunicipio().length()==0){
                    infoTanque.jTextArea1.append(" - Valvula "+count+": Abierta, Municipio: No asignado");
                    infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                }else{
                    infoTanque.jTextArea1.append(" - Valvula "+count+": Abierta, Municipio: "+valv.getMunicipio());
                    infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                }
            }else{
                if(valv.getMunicipio().length()==0){
                    infoTanque.jTextArea1.append(" - Valvula "+count+": Cerrada, Municipio: No asignado");
                    infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                }else{
                    infoTanque.jTextArea1.append(" - Valvula "+count+": Cerrada, Municipio: "+valv.getMunicipio());
                    infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                }
            }
            count++;
        }   
        infot.setVisible(true);
        }catch(Exception e){    
            JOptionPane.showMessageDialog(null, "No hay ningun item seleccionado en el combo box del registro.");
        }
    }//GEN-LAST:event_bInfoActionPerformed

    private void bReestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReestablecerActionPerformed
        // TODO add your handling code here:
        try{
            String ID = cboxRegistro.getSelectedItem().toString(); 
            Tanque tanq = DB.getListaTanques().getTanqueBuscado(ID);
            double temp = tanq.getVolumenTemporal();
            double min = tanq.getVolumenMinimo();
            
            if(temp <= min){
                DB.reestablecerTanqueCualquiera(ID, tanq);
                JOptionPane.showMessageDialog(null, "El tanque con ID "+tanq.getIdentificacion()+" Se ha reestablecido.\n"
                        + "Sus valvulas pueden volverse a operar normalmente.");
            }else{
                JOptionPane.showMessageDialog(null, "El volumen actual todavia no es menor al 25% de\n"
                        + "la capacidad del tanque. Solo se debe de reestablecer\n"
                        + "cuando susceda lo antes dicho. ");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No hay ningun item seleccionado en el combo box del registro.");
        }
    }//GEN-LAST:event_bReestablecerActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        DB.cerrarDB();
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void btanquesRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btanquesRegionActionPerformed
        // TODO add your handling code here:
        try{
        Tanque tanq = new Tanque();
        Tanque[] tanques = DB.listatanques.getTanquesRegion();
        infoTanque infot = new infoTanque();
        
        infoTanque.jTextArea1.append("TANQUES EN EL REGISTRO");
        infoTanque.jTextArea1.append(System.getProperty("line.separator"));
        infoTanque.jTextArea1.append(System.getProperty("line.separator"));
        
        for(int i=0;i<tanques.length;i++){
            tanq = tanques[i];
            if(tanq instanceof TCilindrico){  
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("ID: "+tanq.getIdentificacion());
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("Forma: Cilindrico");
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("Especificaciones: "+tanq.getAltura()+"(alto), "+((TCilindrico)tanq).getRadio()+"(radio)");
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("Capacidad: "+tanq.getCapacidad());
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("Volumen de agua actual: "+tanq.getVolumenTemporal());              
            }else if(tanq instanceof TCubico){
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("ID: "+tanq.getIdentificacion());
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("Forma: Cubico");
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("Especificaciones: "+tanq.getAltura()+"(arista)");
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("Capacidad: "+tanq.getCapacidad());
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("Volumen de agua actual: "+tanq.getVolumenTemporal());
            }else if(tanq instanceof TOrtogonal){
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("ID: "+tanq.getIdentificacion());
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("Forma: Ortogonal");
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("Especificaciones: "+tanq.getAltura()+"(alto)"+((TOrtogonal)tanq).getBase()+"(base)"+((TOrtogonal)tanq).getLargo()+"(largo)");
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("Capacidad: "+tanq.getCapacidad());
                infoTanque.jTextArea1.append(System.getProperty("line.separator"));
                infoTanque.jTextArea1.append("Volumen de agua actual: "+tanq.getVolumenTemporal());
            }
        }
        infot.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No hay tanques en el registro aun.");
        }        
    }//GEN-LAST:event_btanquesRegionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITanques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITanques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITanques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITanques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITanques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbrir;
    private javax.swing.JButton bAsignarMunicipioValvula;
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bCilindrico;
    private javax.swing.JButton bCubico;
    private javax.swing.JButton bInfo;
    private javax.swing.JButton bM3;
    private javax.swing.JButton bOrtogonal;
    private javax.swing.JButton bReestablecer;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton bValvulasCil;
    private javax.swing.JButton btanquesRegion;
    private javax.swing.JComboBox<String> cboxMunicipios;
    private javax.swing.JComboBox<String> cboxRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labeltipo;
    private javax.swing.JPanel panelCilindrico;
    private javax.swing.JPanel panelCubico;
    private javax.swing.JPanel panelMunicipio;
    private javax.swing.JPanel panelOperarTanques;
    private javax.swing.JPanel panelOperarValvulas;
    private javax.swing.JPanel panelOrtogonal;
    private javax.swing.JSpinner spinner1;
    private javax.swing.JSpinner spinner2;
    private javax.swing.JTextField talturacil;
    private javax.swing.JTextField talturacub;
    private javax.swing.JTextField talturaort;
    private javax.swing.JTextField tbase;
    private javax.swing.JTextField tidcil;
    private javax.swing.JTextField tidcub;
    private javax.swing.JTextField tidort;
    private javax.swing.JTextField tlargo;
    private javax.swing.JTextField tradio;
    // End of variables declaration//GEN-END:variables
}
